class InvalidUserException(Exception):
    pass

class UserNotFoundException(Exception):
    pass